config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :availabilities
  resources :meetings do
    member do
      patch :move
      put :start_time
    end
  end
  
  get '/cep/:number', to: 'meetings#cep', as: 'meeting_cep'
  post '/meetings/:id/toggle', to: 'meetings#toggle', as: 'toggle'
  post '/schedulers/:id/toggle_scheduler', to: 'schedulers#toggle_scheduler', as: 'toggle_scheduler'
  get '/meetings/:id/duplicate', to: 'meetings#duplicate', as: 'meeting_duplicate'

  get 'schedulers/show', to: 'schedulers#show', as: 'show'
  get 'schedulers/show-delivers', to: 'schedulers#show_delivers', as: 'show_delivers'
  get 'schedulers/clients-delivers', to: 'schedulers#clients_delivers', as: 'clients_delivers'
  get 'calendar', to: 'availabilities#calendar', as: 'calendar'
  root to: 'schedulers#show'
end

app/models/meeting.rb
class Meeting < ApplicationRecord
	acts_as_list

	def self.sort_position_per_cep(date)
		@meetings = Meeting.where(start_time: Time.parse(date).all_day)
											 .order(cep: :asc)
		@meetings.each_with_index do |meeting, index|
			meeting.update(position: index + 1)
		end		
	end

end

app/controllers/meetings_controller.rb
require 'via_cep'

class MeetingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:move, :start_time]

  before_action :set_meeting, only: [:show, :edit, :update, 
                                     :destroy, :move]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    @availability = Availability.where("start_time <= ?", @meeting[:start_time])
                                .where("end_time >= ?", @meeting[:start_time])

    respond_to do |format|
      if @availability.present?
        @meeting.save
        format.html { redirect_to meetings_path, notice: 'Agendamento feito com sucesso.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    @availability = Availability.where("start_time <= ?", @meeting[:start_time])
                                .where("end_time >= ?", @meeting[:start_time])
    respond_to do |format|
      if @availability.present?
        @meeting.update(meeting_params)
        format.html { redirect_to calendar_path, notice: 'Agendamento Atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Agendamento deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  def toggle
    @meeting = Meeting.find(params[:id])

    if @meeting != nil?
      @meeting.update(message_sent: params[:bool])
      flash[:sucess] = "Salvo com sucesso!"
    else
      flash[:alert] = "Erro, tente novamente"
    end
    head :ok
  end

  def cep
    @address = ViaCep::Address.new(params[:number])
    render json: @address
  end 

  def duplicate
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting != nil?
        meeting_clone = @meeting.dup
        meeting_clone.save
        format.html { redirect_to meetings_path, notice: 'Cópia Agendamento feito com sucesso.' }
      else
        flash[:alert] = "Erro, tente novamente"
      end
    end
  end

  def move
    @meeting.insert_at(params[:position].to_i)
    head :ok
  end  

  def start_time
    @meeting = Meeting.find(params[:id])
    if @meeting != nil?
      @meeting.update(start_time: DateTime.parse("#{@meeting.start_time.strftime("%Y-%m-%d")} #{params[:start_time]}"))
      flash[:sucess] = "Salvo com sucesso!"
    else
      flash[:alert] = "Erro, tente novamente"
    end
    head :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :localization, :phone, :start_time, :products, :total_price, 
                                      :payment_type, :information, :district, :message_sent, :package_ready,
                                      :cep)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for @meeting, :html => { :class => "form-horizontal meeting", novalidate: true } do |f| %>

  <% if @meeting.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:name), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :cep, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cep, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:localization) %>
  </div>   
  <div class="form-group">
    <%= f.label t(:localization), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :localization, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:localization) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:district), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :district, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:district) %>
  </div>
  <div class="form-group">
    <%= f.label t(:phone), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label t(:start_time), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= datetime_local_field :meeting, :start_time, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:start_time) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:products), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_area :meeting, :products, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:products) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:total_price), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_field :meeting, :total_price, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:total_price) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:payment_type), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_field :meeting, :payment_type, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:payment_type) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:information), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_area :meeting, :information, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:information) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<script type="text/javascript">
let inputCep = document.querySelector('#meeting_cep');

inputCep.addEventListener('blur', function() {
  fetch('/cep/' + inputCep.value).then(function (res) {
      if (res.ok) {
          return res.json();
      }
  }).then(function (data) {
    document.querySelector('#meeting_localization').value = data.response.logradouro;
    document.querySelector('#meeting_district').value = data.response.bairro + ' - ' + data.response.localidade + '/' + data.response.uf ;
  }).catch(function (err) {
      return console.log(err);
  });
})

</script>

app/views/meetings/_form_edit.html.erb
<%= form_for @meeting, :html => { :class => "form-horizontal meeting", novalidate: true } do |f| %>

  <% if @meeting.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @meeting.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label t(:name), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :cep, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :cep, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:cep) %>
  </div>    
  <div class="form-group">
    <%= f.label t(:localization), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :localization, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:localization) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:district), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :district, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:district) %>
  </div>
  <div class="form-group">
    <%= f.label t(:phone), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :phone, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:phone) %>
  </div>
  <div class="form-group">
    <%= f.label t(:start_time), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= datetime_local_field :meeting, :start_time, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:start_time) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:products), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_area :meeting, :products, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:products) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:total_price), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_field :meeting, :total_price, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:total_price) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:payment_type), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_field :meeting, :payment_type, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:payment_type) %>
  </div>  
  <div class="form-group">
    <%= f.label t(:information), :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= text_area :meeting, :information, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:information) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>


<script type="text/javascript">
let inputCep = document.querySelector('#meeting_cep');

inputCep.addEventListener('blur', function() {
  fetch('/cep/' + inputCep.value).then(function (res) {
      if (res.ok) {
          return res.json();
      }
  }).then(function (data) {
    document.querySelector('#meeting_localization').value = data.response.logradouro;
    document.querySelector('#meeting_district').value = data.response.bairro + ' - ' + data.response.localidade + '/' + data.response.uf ;
  }).catch(function (err) {
      return console.log(err);
  });
})

</script>

app/views/meetings/edit.html.erb
<%- model_class = Meeting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form_edit' %>

app/views/meetings/index.html.erb
<%- model_class = Meeting -%>
<div class="page-header">
  <h1><%=t '.title', :default => t(model_class.model_name.human.pluralize.titleize) %></h1>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_meeting_path,
            :class => 'btn btn-primary' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t model_class.human_attribute_name(:id) %></th>
      <th><%= t model_class.human_attribute_name(:name) %></th>
      <th><%= t model_class.human_attribute_name(:localization) %></th>
      <th><%= t model_class.human_attribute_name(:phone) %></th>
      <th><%= t model_class.human_attribute_name(:start_time) %></th>
      <th><%= t model_class.human_attribute_name(:created_at) %></th>
      <th>Mensagem Whatsapp</th>
      <th>Mensagem enviada?</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= link_to meeting.id, meeting_path(meeting) %></td>
        <td><%= meeting.name %></td>
        <td><%= meeting.localization %></td>
        <td><%= meeting.phone %></td>
        <td><%=l meeting.start_time %></td>
        <td><%=l meeting.created_at %></td>
        <td><a href="https://web.whatsapp.com/send?phone=55<%= meeting.phone %>&amp;text=Oie <%= meeting.name.split(' ')[0] %>, tudo bom!! Sou a Lari da Purchase. Estou organizando os pedidos para entrega de motoboy hoje. Estou confirmando sua entrega por volta das <%= meeting.start_time.strftime("%H:%M") %>." target="_blank">Clique Aqui para mandar uma mensagem pelo WhatsApp</a></td>
        <td><%= check_box_tag 'message_sent', meeting.id, meeting.message_sent, class: 'message_sent' %></td>
        <td>
          <%= link_to t('.duplicate', :default => t("helpers.links.duplicate")),
                      meeting_duplicate_path(meeting), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_meeting_path(meeting), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      meeting_path(meeting),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
 
  var checkbox = document.querySelectorAll(".message_sent");

  checkbox.forEach(function(check, index) {
    check.addEventListener('change', function() {
      fetch('/meetings/' + this.value + '/toggle', {
        method: 'post',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').getAttribute('content')
        },
        body: JSON.stringify({bool: this.checked})
      }).then(function (res) {
        console.log('OK');
      }).catch(function (err) {
          return console.log(err);
      });
    });
  });

</script>

app/views/meetings/new.html.erb
<%- model_class = Meeting -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => t(model_class.model_name.human.titleize) %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meetings/show.html.erb
<%- model_class = Meeting -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @meeting.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:localization) %>:</strong></dt>
  <dd><%= @meeting.localization %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @meeting.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
  <dd><%= @meeting.start_time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              meetings_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_meeting_path(@meeting), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              meeting_path(@meeting),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>