config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :availabilities
  resources :meetings do
    member do
      patch :move
      put :start_time
    end
  end
  
  get '/cep/:number', to: 'meetings#cep', as: 'meeting_cep'
  post '/meetings/:id/toggle', to: 'meetings#toggle', as: 'toggle'
  post '/schedulers/:id/toggle_scheduler', to: 'schedulers#toggle_scheduler', as: 'toggle_scheduler'
  get '/meetings/:id/duplicate', to: 'meetings#duplicate', as: 'meeting_duplicate'

  get 'schedulers/show', to: 'schedulers#show', as: 'show'
  get 'schedulers/show-delivers', to: 'schedulers#show_delivers', as: 'show_delivers'
  get 'schedulers/clients-delivers', to: 'schedulers#clients_delivers', as: 'clients_delivers'
  get 'calendar', to: 'availabilities#calendar', as: 'calendar'
  root to: 'schedulers#show'
end

app/models/availability.rb
class Availability < ApplicationRecord
end

app/controllers/availabilities_controller.rb
class AvailabilitiesController < ApplicationController
  before_action :set_availability, only: [:show, :edit, :update, :destroy]

  # GET /availabilities
  # GET /availabilities.json
  def index
    @availabilities = Availability.all
  end

  # GET /availabilities/1
  # GET /availabilities/1.json
  def show
  end

  # GET /availabilities/new
  def new
    @availability = Availability.new
  end

  # GET /availabilities/1/edit
  def edit
  end

  # POST /availabilities
  # POST /availabilities.json
  def create
    @availability = Availability.new(availability_params)

    respond_to do |format|
      if @availability.save
        format.html { redirect_to availabilities_path, notice: 'Availability was successfully created.' }
        format.json { render :show, status: :created, location: @availability }
      else
        format.html { render :new }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /availabilities/1
  # PATCH/PUT /availabilities/1.json
  def update
    respond_to do |format|
      if @availability.update(availability_params)
        format.html { redirect_to availabilities_path, notice: 'Availability was successfully updated.' }
        format.json { render :show, status: :ok, location: @availability }
      else
        format.html { render :edit }
        format.json { render json: @availability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /availabilities/1
  # DELETE /availabilities/1.json
  def destroy
    @availability.destroy
    respond_to do |format|
      format.html { redirect_to availabilities_url, notice: 'Availability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def calendar
    @availabilities = Availability.all
    @meetings = Meeting.all
    respond_to do |format|
      format.html
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_availability
      @availability = Availability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def availability_params
      params.require(:availability).permit(:localization, :start_time, :end_time)
    end
end

app/helpers/availabilities_helper.rb
module AvailabilitiesHelper
end

app/views/availabilities/_form.html.erb
<%= form_for @availability, :html => { :class => "form-horizontal availability" } do |f| %>

  <% if @availability.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@availability.errors.count, "error") %> prohibited this availability from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @availability.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :localization, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :localization, :class => 'form-control', :required => true %>
    </div>
    <%=f.error_span(:localization) %>
  </div>
  <div class="form-group">
    <%= f.label :start_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= datetime_local_field(:availability, :start_time, :required => true) %>
    </div>
    <%=f.error_span(:start_time) %>
  </div>
  <div class="form-group">
    <%= f.label :end_time, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= datetime_local_field(:availability, :end_time, :required => true) %>
    </div>
    <%=f.error_span(:end_time) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                availabilities_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/availabilities/calendar.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>
<%= month_calendar events: @availabilities do |date, availabilities| %>
  <%= l(date) %><br>
  <% if date >= Date.today %>
    <% if availabilities.empty?%>
      <div>Indisponível</div>
    <% else %>
      <% availabilities.each do |availability| %>
        <div><%= availability.localization %></div>
        <div>Das <%= availability.start_time.strftime("%H:%M") %> às <%= availability.end_time.strftime("%H:%M") %></div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/availabilities/edit.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/availabilities/index.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => t(model_class.model_name.human.pluralize.titleize) %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:localization) %></th>
      <th><%= model_class.human_attribute_name(:start_time) %></th>
      <th><%= model_class.human_attribute_name(:end_time) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @availabilities.each do |availability| %>
      <tr>
        <td><%= link_to availability.id, availability_path(availability) %></td>
        <td><%= availability.localization %></td>
        <td><%= availability.start_time %></td>
        <td><%= availability.end_time %></td>
        <td><%=l availability.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_availability_path(availability), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      availability_path(availability),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_availability_path,
            :class => 'btn btn-primary' %>

app/views/availabilities/new.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/availabilities/show.html.erb
<%- model_class = Availability -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:localization) %>:</strong></dt>
  <dd><%= @availability.localization %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_time) %>:</strong></dt>
  <dd><%= @availability.start_time %></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_time) %>:</strong></dt>
  <dd><%= @availability.end_time %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              availabilities_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_availability_path(@availability), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              availability_path(@availability),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>