config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :availabilities
  resources :meetings do
    member do
      patch :move
      put :start_time
    end
  end
  
  get '/cep/:number', to: 'meetings#cep', as: 'meeting_cep'
  post '/meetings/:id/toggle', to: 'meetings#toggle', as: 'toggle'
  post '/schedulers/:id/toggle_scheduler', to: 'schedulers#toggle_scheduler', as: 'toggle_scheduler'
  get '/meetings/:id/duplicate', to: 'meetings#duplicate', as: 'meeting_duplicate'

  get 'schedulers/show', to: 'schedulers#show', as: 'show'
  get 'schedulers/show-delivers', to: 'schedulers#show_delivers', as: 'show_delivers'
  get 'schedulers/clients-delivers', to: 'schedulers#clients_delivers', as: 'clients_delivers'
  get 'calendar', to: 'availabilities#calendar', as: 'calendar'
  root to: 'schedulers#show'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Agendador</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      <li><a href="<%= availabilities_path %>">Disponibilidades do entregador</a></li>
      <li><a href="<%= clients_delivers_path %>">Calendário Agendamentos Clientes</a></li>
      <li><a href="<%= show_path %>">Calendário Agendamentos Entregador Mensal</a></li>
      <li><a href="<%= show_delivers_path %>">Calendário Agendamentos Entregador Diário</a></li>
      <li><a href="<%= meetings_path %>">Lista de agendamentos clientes</a></li>
      <li><a href="<%= edit_user_registration_path %>">Editar perfil</a></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agendamento de entrega</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="https://image.flaticon.com/icons/png/512/1647/1647543.png" />
    <link rel="manifest" href="/manifest.json" />
    <meta name="apple-mobile-web-app-capable" content="yes">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render :partial => 'layouts/navbar' %>
    <% else %>
      <%#= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %>
      <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <p class="navbar-text float-right">
    <%= yield %>
  </body>
</html>